# Generated by Django 5.0.4 on 2024-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_content_post_id_alter_post_number_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.AutoField(db_column='번호', primary_key=True, serialize=False),
        ),
    ]
